# Generated by Django 5.0.2 on 2025-10-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naomi_sistemaescolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestros',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
