# Generated by Django 5.0.2 on 2025-11-29 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naomi_sistemaescolar_api', '0005_maestros_area_investigacion_maestros_id_maestro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_event', models.CharField(max_length=255)),
                ('tipo_evento', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('objetivo_json', models.TextField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('Asistentes', models.TextField(blank=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
